auth:
  type: oauth2
  oauth2:
    clientid: ""
    clientsecret: ""
    accesstokenoverride: ""
    authurl: "https://accounts.google.com/o/oauth2/v2/auth"
    tokenurl: "https://oauth2.googleapis.com/token"
    revocationurl: "https://oauth2.googleapis.com/revoke"
    redirecturl: "http://localhost:43296/redirect"
  smtp:
    address: "smtp.gmail.com"
  imap:
    address: "imap.gmail.com"
    poll: "5s"
mailboxes:
- "INBOX"
- "[Gmail]/Spam"
identity:
  address: "alexj.pauwels@gmail.com"
  name: "Alexandre Pauwels"
  secretkey: {}
addressbook:
- address: "johncamacuk@gmail.com"
  name: "John Camacuk Gmail"
  publickey:
    nacl: "xDaZE2I9pPfagsxv4T4XYKFFEBZll3+5jIVzFX/0STo="
- address: "johncamacuk@yahoo.com"
  name: "John Camacuk Yahoo"
  publickey:
    nacl: "W+7h6HeuHBYuybIWGMhYkpki2eXW3Oao9wORYcc5yR8="
