auth:
  type: "oauth2"
  password: ""
  oauth2:
    clientid: ""
    clientsecret: ""
    accesstokenoverride: ""
    authurl: "https://accounts.google.com/o/oauth2/v2/auth"
    tokenurl: "https://oauth2.googleapis.com/token"
    revocationurl: "https://oauth2.googleapis.com/revoke"
    redirecturl: "http://localhost:43296/redirect"
  smtp:
    address: "smtp.gmail.com"
  imap:
    address: "imap.gmail.com"
    poll: "5s"
mailboxes:
- "INBOX"
- "[Gmail]/Spam"
identity:
  address: "alexj.pauwels@gmail.com"
  name: "Alexandre Pauwels"
  # secretkey:
  #   nacl: ""
  #   dalek: ""
addressbook:
- address: "johncamacuk@yahoo.com"
  name: "John Camacuk Yahoo"
  publickey:
    # nacl: "epAb3uco5DyZv/ZTVnwfPsG66+uIuamsssHOILQCJgE="
    dalek: "o42ZHseYE1W2ydS9Qk65z1Tk2K/N8nnu4C++TFWjJn4="
- address: "johncamacuk@gmail.com"
  name: "John Camacuk Gmail"
  publickey:
    # nacl: "o4mURQM/IxWVnpWyw9toVR1QItGdLeW7QHu8x9+DPn4="
    dalek: "dYbvsW7JV9g29AYqqabdJsgR1qSdlG8mZQYlYWXjLV4="
